### PR TITLE
.NET Standard

### PR DESCRIPTION
**Pull request by Cazzar**
Pushing this PR for feedback and looking for any issues with the current .NET 4 version

@da3dsoul would be best to verify that the GroupFilter changes done are needed.
the Group Filter repo didn't conflict, that's because the file was moved into repositories_old and rebuilt from the ground up

### CODE REVIEW

**Comment by da3dsoul** [comment]
@cazzar how do pull a pull request for editing. Can I commit straight to a pull request, or do I need to pull your fork and PR against yours for the conflicts?

**Comment by da3dsoul** [comment]
Right.... I spaced that it was just a branch

**Comment by da3dsoul** [comment]
I need to sleep

**Comment by bigretromike** [comment]
@Cazzar congratulation. Milestone of this project !

**Pull request merged**
