### PR TITLE
sysvar programData

### PR DESCRIPTION
**Pull request by 1ijack**
- replaced all "C:\ProgramData%\ShokoServer" with "%ProgramData%\ShokoServer"
- added double-quotes across all ProgramData path references, to insure path validity for mkdir and icacls
- replaced redunent [if not exist...] statement with [ else ]

### CODE REVIEW

**Comment by 1ijack** [comment]
Maybe I'm jumping the gun with this pull request on a unless throw-away script, but I find system variables more friendlier across different envs.

**Comment by bigretromike** [comment]
Looks fine. Good work !

**Comment by ElementalCrisis** [comment]
Thanks for the PR!

**Comment by 1ijack** [comment]
@ElementalCrisis no worries, yeah PRs are great, it's just one less thing that you guys need to worry about. 
 btw, if you need any windows batch/cmd-console help/work done, let me know.

**Comment by ElementalCrisis** [comment]
I appreciate it! 

Not sure if we need anything else right now but hop on our Discord as we'll probably post there first.

**Pull request merged**
