### PR TITLE
Fix: Avoid the logout timer trying to acquire the lock twice

### PR DESCRIPTION
**Pull request by fearnlj01**

### CODE REVIEW

**Comment by fearnlj01** [comment]
Woops, didn't mean to submit that without comment... But some experimentation suggested that `LogoutTimerElapsed` would acquire a lock, preventing the actual logout command from being able to lock.

(I think)

**Comment by da3dsoul** [comment]
Have you tested that it at least logs out as expected?

**Comment by fearnlj01** [comment]
I've done so when I had the logout timer set to two minutes, but can give it a more natural run on what I'm running now.

Will confirm again in ~5 minutes

**Comment by fearnlj01** [comment]
Confirming that it logs out as expected in the "normal" test run, and allows for an immediate re-login afterwards without any errors 👍

**Pull request merged**
