### PR TITLE
CommandRequest query optimisations.

### PR DESCRIPTION
**Pull request by bond4u**
Take(1) and RowCount() instead of just List().

### CODE REVIEW

**Comment by da3dsoul** [comment]
I appreciate the effort, but I'm going to reject this for one reason: It's going to need to be like that for Queue Factory, as there's going to need to be more complex selection of the next command.
The RowCount ones can stay

**Comment by da3dsoul** [comment]
Actually I'll just tweak it a bit. Remove the obsolete tags as we'll need them later, and it's good

**Comment by bond4u** [comment]
what's wrong with Take(1) ?

**Comment by da3dsoul** [comment]
Because you can use UniqueResult instead

**Comment by hidden4003** [comment]
So that is why large queues are so slow... @da3dsoul what is wrong with Take(1)? should be good we have full refactor planned in the near future anyways should be fine as a hotfix

**Comment by Cazzar** [comment]
Personally speaking, I would refactor this a little more to dynamically generate the commands to not try.
This could be done via the annotation
https://github.com/ShokoAnime/ShokoServer/blob/c34eadfd61b3621258410fe7ea418c810fde77e3/Shoko.Server/Commands/CommandRequestImplementation.cs#L16-L22
Adding an enum/flag to say:
```csharp
[Flags]
enum AniDBBan {
    Http = 1, Udp = 2, None = 0
}
```
and filter it out on the attribute, as we would already scan the available types here:
https://github.com/ShokoAnime/ShokoServer/blob/c34eadfd61b3621258410fe7ea418c810fde77e3/Shoko.Server/Commands/CommandHelper.cs#L110-L127

If we classify them dynamically, I don't see why this wouldn't work.

At a minimum, we should limit the result count, but that's harder to manage.
This would also work for designing around to the Queue Factory setup, as with this, we could designate which queue it's in dynamically.

**Comment by da3dsoul** [comment]
Nothing is wrong with Take(1). What is wrong is returning List instead of UniqueResult

**Comment by da3dsoul** [comment]
It creates an enumerable and counts all 1 item instead of using the one item we asked for

**Comment by bond4u** [comment]
In case of mysql, Take(1) resulted query with "limit 1".

**Comment by da3dsoul** [comment]
Ugh

**Comment by da3dsoul** [comment]
```
crs = session.QueryOver<CommandRequest>()
.WhereRestrictionOn(field => field.CommandType)
.IsIn(types.ToArray())
.OrderBy(cr => cr.Priority).Asc
.ThenBy(cr => cr.DateTimeUpdated).Asc
.Take(1)
.UniqueResult<CommandRequest>();
```

**Comment by da3dsoul** [comment]
That'll error, but that's what I meant

**Comment by bond4u** [comment]
CommandRequest cr = session
                        .CreateCriteria(typeof(CommandRequest))
                        .Add(Restrictions.In("CommandType", cTypes.ToArray()))
                        .AddOrder(Order.Asc("Priority"))
                        .AddOrder(Order.Asc("DateTimeUpdated"))
                        .SetMaxResults(1)
                        .UniqueResult<CommandRequest>();
UniqueResult seems to be doing some post-processing, because it throws when resultset contains more than one row. So You have to add SetMaxResults(1) which does "limit 1" query and You get single row.
But I don't like hardcoded strings.
QueryOver...Take(1).SingleOrDefault() with field names looks better.

**Comment by da3dsoul** [comment]
Fair

**Pull request merged**
